### ISSUE TITLE
Problem compiling project

### ISSUE THREAD

**Issue by pvilaca** [biotextmining/processes#3]
@Ru13en 

I think there are some problems in repositories declared in `pom.xml` of this project:

```xml
<repositories>
	<repository>
		<id>thirdparty</id>
		<url>
		http://mendel.di.uminho.pt:8081/nexus/content/repositories/thirdparty/
		</url>
	</repository>
	<repository>
		<id>ebi</id>
		<url>http://www.ebi.ac.uk/intact/maven/nexus/content/repositories/ebi-repo/</url>
	</repository>
</repositories>
```
[build info](https://travis-ci.org/biotextmining/processes/builds/597758072)

Can we remove this repositories?

**Comment by pvilaca** [comment]
I solved this problem changed  the thirdparty repository url to `http:/nexus.bio.di.uminho.pt/content/repositories/thirdparty` on 2153bd9. 

Now the project has a dependency problem:
>>>
[ERROR] Failed to execute goal on project processes: Could not resolve dependencies for project com.silicolife.textmining:processes:jar:0.0.0-SNAPSHOT: Failed to collect dependencies at org.wipo:patentscope:jar:1.2: Failed to read artifact descriptor for org.wipo:patentscope:jar:1.2: Could not transfer artifact org.wipo:patentscope:pom:1.2 from/to thirdparty (http:/nexus.bio.di.uminho.pt/content/repositories/thirdparty): URI does not specify a valid host name: http:/nexus.bio.di.uminho.pt/content/repositories/thirdparty/org/wipo/patentscope/1.2/patentscope-1.2.pom -> [Help 1]
>>>

more details [here](https://travis-ci.org/biotextmining/processes)

@Ru13en , @a41033uminho, @TAPAlves, Do you know where is this jar ?

**Comment by a41033uminho** [comment]
As far as I can remember this jar was in Mendel Nexus

**Comment by pvilaca** [comment]
@a41033uminho I thought so too. But I can't find it. 

@Ru13en can you help on this?

**Comment by pvilaca** [comment]
@a41033uminho Do you know if I can download the jar anywhere else?

**Comment by a41033uminho** [comment]
I don't think so, it was a jar given by wipe when we paid for the service. But probably I have it on my maven trash thinks

**Comment by Ru13en** [comment]
If it is in mendel I will put it on our Nexus. After lunch I will do it.

**Comment by Ru13en** [comment]
Now they are accessible by this:
https://nexus.bio.di.uminho.pt/content/repositories/thirdparty/org/wipo/
(i will check all jars in mendel to put in our nexus, removing the nexus on mendel completely).

**Comment by pvilaca** [comment]
It's working now!! Thanks!
